name: Coverage

on:
  push:
    branches:
      - main
  pull_request:

permissions:
   contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codecov:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Install packages
      run: sudo apt-get install -y lcov

    - name: Configure
      run: cmake -DCMAKE_BUILD_TYPE=Coverage -S . -B build
    - name: Build
      run: cmake --build build
    - name: Run Tests
      working-directory: build
      run: ctest
    - name: Generating coverage report
      run: cmake --build build --target coverage_html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882  # v4.4.3
      with:
        name: cov-html
        path: build/coverage_report/**

    - name: Upload coverage
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238  # v4.6.0
      with:
        file: build/coverage.info
        token: ${{secrets.CODECOV_TOKEN}}
        verbose: true
